### ISSUE TITLE
How to use it?

### ISSUE THREAD

**Issue by ProdigyMaster** [Calvin-Huang/vue-amplitude#1]
Hey, can you provide example how to send event using this library? Thanks

**Comment by jonreeves** [comment]
Looking at the src file I can see that it just initializes the amplitude script and attaches the object to a prop on the Vue object.

I think you should be able to access the amplitude object from `Vue.$amplitude` or `this.$amplitude` while inside a Vue component file.

So a command like `this.$amplitude.logEvent('EVENT_NAME', { key: 'value' })` should be possible.

It doesn't appear to support Multiple Projects right now as no param is passed through to the `getInstance` method: https://developers.amplitude.com/#logging-events-to-multiple-projects

**Comment by molinto** [comment]
Yep, needs a lot more info on how to use it please.

Used to track events? Identities?

Thanks

**Comment by mikedidthis** [comment]
> So a command like `this.$amplitude.logEvent('EVENT_NAME', { key: 'value' })` should be possible.

Just to clarify it should be `this.$amplitude.getInstance().logEvent()`.

**Comment by Calvin-Huang** [comment]
Thanks for your support! If everything is okay, I'll close this issue. 🙂
